### ISSUE TITLE
[共通]MySQL テーブル作成

### ISSUE THREAD

**Issue by towa1204** [NT-Dentsu/dentsuTools2#1]
# 概要

dentsuToolsで作成していたMySQLのテーブルをdentsuTools2に移行する。
具体的には、dentsuToolsでは、.sqlファイルにテーブルの定義を記載していたが、dentsuTools2ではlaravelなのでmigrationファイルに記載する。

また、移行にあたってテーブルの定義を変更する可能性がある。

# 補足

[migration](https://readouble.com/laravel/9.x/ja/migrations.html)

**Comment by KARASU-2000** [comment]
※Webhookの確認用コメント

**Comment by KARASU-2000** [comment]
Discord通知検証コメント

**Comment by KARASU-2000** [comment]
Discord通知検証コメント
